app/__init__.py
from flask import Flask
from config import Config
from flask_session import Session

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    from app import routes
    app.register_blueprint(routes.bp)

    Session(app)

    return app

app/routes.py
from flask import Blueprint, redirect, url_for, session, request, render_template
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from flask import current_app as app
import os

bp = Blueprint('routes', __name__)


@bp.route('/')
def index():
    sp_oauth = SpotifyOAuth(client_id=app.config['SPOTIPY_CLIENT_ID'],
                            client_secret=app.config['SPOTIPY_CLIENT_SECRET'],
                            redirect_uri=app.config['SPOTIPY_REDIRECT_URI'],
                            scope="user-top-read")

    auth_url = sp_oauth.get_authorize_url()
    return render_template('index.html', auth_url=auth_url)


@bp.route('/callback')
def callback():
    sp_oauth = SpotifyOAuth(client_id=app.config['SPOTIPY_CLIENT_ID'],
                            client_secret=app.config['SPOTIPY_CLIENT_SECRET'],
                            redirect_uri=app.config['SPOTIPY_REDIRECT_URI'],
                            scope="user-top-read")

    session.clear()
    code = request.args.get('code')
    try:
        token_info = sp_oauth.get_access_token(code)
        session["token_info"] = token_info
    except Exception as e:
        print(f"Error getting token: {e}")
        return redirect(url_for('routes.index'))

    return redirect(url_for('routes.top_items'))


@bp.route('/top_items')
def top_items():
    token_info = session.get("token_info", None)
    if not token_info:
        return redirect(url_for('routes.index'))

    sp = spotipy.Spotify(auth=token_info['access_token'])
    try:
        top_tracks = sp.current_user_top_tracks(limit=5, time_range='medium_term')
        top_artists = sp.current_user_top_artists(limit=5, time_range='medium_term')

        # Collecting genres
        genres = []
        for artist in top_artists['items']:
            genres.extend(artist['genres'])

        # Choosing the 5 most listened to genres
        from collections import Counter
        top_genres = [genre for genre, _ in Counter(genres).most_common(5)]

    except spotipy.SpotifyException as e:
        print(f"Spotify API error: {e}")
        return redirect(url_for('routes.index'))

    # Get necessary information for songs and artists
    top_tracks_info = [{
        'name': track['name'],
        'image': track['album']['images'][0]['url'],
        'url': track['external_urls']['spotify']
    } for track in top_tracks['items']]

    top_artists_info = [{
        'name': artist['name'],
        'image': artist['images'][0]['url'],
        'url': artist['external_urls']['spotify']
    } for artist in top_artists['items']]

    return render_template('top_items.html', top_tracks=top_tracks_info, top_artists=top_artists_info,
                           top_genres=top_genres)


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('routes.index'))

app/templates/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Welcome — Spotify Stats</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
  <h1>SPOTIFY STATS</h1>
  <p class="main">Take a look at the songs, artists and genres you listen to most in the medium term.</p>
  <div class="button-container">
    <a href="{{ auth_url }}"><button>Login with Spotify</button></a>
  </div>
  <p class="footer">Project coded by <a href="https://mesci.dev/" target="_blank">Yusuf Mescioğlu</a>, shout-out to <a href="https://twitter.com/juxtopposed" target="_blank">Juxtopposed</a> for login button.</p>
</body>
</html>

app/templates/top_items.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Results — Spotify Stats</title>
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<div class="wrapper">
  <div class="heazer">
  <div class="title-1"><h1> Top Songs </h1></div>
  <div class="buttons">
    <a href="{{ url_for('routes.logout') }}"><button class="btn-hover color-1">Log out</button></a>
</div>
</div>
  <div class="cards-grid">
    <div class="card">
      <a href="{{ top_tracks[0].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_tracks[0].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">Listen on Spotify &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_tracks[0].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_tracks[1].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_tracks[1].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">Listen on Spotify &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_tracks[1].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_tracks[2].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_tracks[2].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">Listen on Spotify &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_tracks[2].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_tracks[3].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_tracks[3].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">Listen on Spotify &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_tracks[3].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_tracks[4].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_tracks[4].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">Listen on Spotify &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_tracks[4].image }}" />
        </div>
      </a>
    </div>
  </div>
  <div class="title-1"><h1> Top Artists </h1></div>
  <div class="cards-grid">
    <div class="card">
      <a href="{{ top_artists[0].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_artists[0].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">View Profile &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_artists[0].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_artists[1].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_artists[1].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">View Profile &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_artists[1].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_artists[2].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_artists[2].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">View Profile &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_artists[2].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_artists[3].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_artists[3].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">View Profile &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_artists[3].image }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="{{ top_artists[4].url }}" class="card-link" target="_blank">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_artists[4].name }}</h3>
          <div class="alt-text"><span class="card-mimin-link">View Profile &rsaquo;</span></div>
        </span>
        <div class="card-image">
          <img src="{{ top_artists[4].image }}" />
        </div>
      </a>
    </div>
  </div>
  <div class="title-1"><h1> Top Genres </h1></div>
  <div class="cards-grid">
    <div class="card">
      <a href="#" style="cursor:default;" class="card-link">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_genres[0] }}</h3>
          <div class="alt-text"><span class="card-mimin-link">#1</span></div>
        </span>
        <div class="card-image">
          <img src="{{ url_for('static', filename='images/Genre_1.png') }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#" style="cursor:default;" class="card-link">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_genres[1] }}</h3>
          <div class="alt-text"><span class="card-mimin-link">#2</span></div>
        </span>
        <div class="card-image">
          <img src="{{ url_for('static', filename='images/Genre_2.png') }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#" style="cursor:default;" class="card-link">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_genres[2] }}</h3>
          <div class="alt-text"><span class="card-mimin-link">#3</span></div>
        </span>
        <div class="card-image">
          <img src="{{ url_for('static', filename='images/Genre_3.png') }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#" style="cursor:default;" class="card-link">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_genres[3] }}</h3>
          <div class="alt-text"><span class="card-mimin-link">#4</span></div>
        </span>
        <div class="card-image">
          <img src="{{ url_for('static', filename='images/Genre_4.png') }}" />
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#" style="cursor:default;" class="card-link">
        <span class="card-overlay">
          <h3 class="card-title">{{ top_genres[4] }}</h3>
          <div class="alt-text"><span class="card-mimin-link">#5</span></div>
        </span>
        <div class="card-image">
          <img src="{{ url_for('static', filename='images/Genre_5.png') }}" />
        </div>
      </a>
    </div>
  </div>
<div class="footer">
<p>Coded by <a href="https://mesci.dev/" id="my-link" target="_blank"><strong>Yusuf Mescioğlu</strong></a></p>
</div>
</div>
</body>
</html>